### ISSUE TITLE
Column headers not getting pulled into CSV export

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#123]
> Column headers not getting pulled into data export

**Comment by karmour** [comment]
Confirmed in Edge. 
@stephanieyurchak can you confirm in Chrome?

**Comment by stephanieyurchak** [comment]
I saved the Indigenous table on the representation tab as csv. I do get column headers but I also get an Â in the headers for Total, Indigenous as % of Available Workforce and Expected # Indigenous. I assumed this is due to the tool tip, but there is not an Â  appearing in the Shortfall header. Is it possible to remove the Â from the column headers in the export?

**Comment by karmour** [comment]
Thanks Steph, I missed those. Yes they appear to be attached to columns with tooltips (except Shortfall -- maybe because Shortfall doesn't have a tooltip in 2018?). @hangler can you investigate?

**Comment by hangler** [comment]
Should be removed now.

**Comment by karmour** [comment]
I'm still seeing the odd characters in the data exports on the Representation tab, so I think this hasn't made it into the active deployment. Will move ticket to Final Tidying.

**Comment by hangler** [comment]
I don't see this on Chrome on Mac, but I will double-check on Windows.

**Comment by karmour** [comment]
Checked this afternoon after clearing cache and they appear to be gone in Edge! @stephanieyurchak can you re-check in Chrome?

**Comment by stephanieyurchak** [comment]
Confirmed in Chrome
