### ISSUE TITLE
2020 JEDC data not displaying

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#124]
> 2020 JEDC data does not display – possible connection to the entry in the filter menu still has old 2018 label of "Jobs, Trade and Technology" (should be year-dependent)

**Comment by karmour** [comment]
This appears fixed. One side note, if I have JEDC as my filter for 2020 and then select 2018, then the filter gets unchecked and the visualization appears as blank, because the tool doesn't know that JEDC in 2020 and JTT in 2018 are essentially the same organization. I think this is OK - the user can then find JTT in the filter list and re-select it.

**Comment by hangler** [comment]
OK, great.
