### ISSUE TITLE
Add Active Filters box to the Ministry tab

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#81]
Currently not showing.

**Comment by hangler** [comment]
Done.

**Comment by karmour** [comment]
It now shows up, but seeing it, I realize it must have been hidden on purpose previously, as the Active Filters lists all filters including the designated groups. But each visual on the page only shows a single designated group, so the full list of designated groups is misleading. 

I do see a sub-heading that lists the designated group and the employee type filter (although it currently isn't working and always says "regular employees"). Presumably this sub-header was intended to act as a list of active filters on the visual. Perhaps we could re-purpose that sub-header to display the designated group > organization > employee type > year? Then we could re-hide the Active Filters box (sorry!). 

Additionally, we may need to add an entry for "S" in the Legend below the "<3" entry, since we do have some data points with "S" on this tab too.

**Comment by karmour** [comment]
@stephanieyurchak pointed out to me that the Organization filter is irrelevant on the Organizations tab anyway, so let's leave that field out of the solution regardless. If we go with my suggestion above to use the sub-header above each chart to list the filters, then let's use Designated Group > Employee Type > Year.

A more attractive alternative (i.e., nice-to-have) to putting all of the filters in the sub-heading above each chart would be to crop the Active Filters box to only show Data Year and Employee Type. Then the sub-heading could be limited to only including the Designated Group.

**Comment by hangler** [comment]
Implemented the more attractive alternative :-)

**Comment by karmour** [comment]
Thank you! :-) However, I'm not seeing this change in the live version, so perhaps it's still waiting for the next deployment? Will move to Final Tidying milestone.

**Comment by hangler** [comment]
This should be in the latest deployment.

**Comment by karmour** [comment]
The new Active Filters box on the Organizations tab is definitely more attractive now. :-)

Can you also put the "S" entry into the Legend underneath the entry for "<3"? Thank you!

**Comment by hangler** [comment]
Now deployed. Looks like this:

<img width="310" alt="Screen Shot 2021-04-19 at 1 54 42 PM" src="https://user-images.githubusercontent.com/3538990/115302058-d7fd8280-a116-11eb-9cd5-5a9077c5a784.png">

**Comment by karmour** [comment]
Looks good in Edge and Chrome, and also gets pulled into the Save as PNG. Thank you!

**Comment by karmour** [comment]
Just noticed that the Save as PNG is now duplicating the designated group name in the title overlay, instead of taking the "BC Public Service, XXXX employees" line. Can this be fixed?

**Comment by hangler** [comment]
Done and deployed.

**Comment by karmour** [comment]
Looks good!
